#define PY_ZIP="https://www.python.org/ftp/python/3.8.9/python-3.8.9-embed-amd64.zip"
#define PY_PIP="https://bootstrap.pypa.io/get-pip.py"
#define req = "requirements-3.8.txt"
#define Output = "CO-PO.3.8"
#include "setup.iss"
